//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightedDictionary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeightedDictionary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Valence
        ///_intercept	0
        ///abandon	-2
        ///abandoned	-2
        ///abandons	-2
        ///abducted	-2
        ///abduction	-2
        ///abductions	-2
        ///abhor	-3
        ///abhorred	-3
        ///abhorrent	-3
        ///abhors	-3
        ///abilities	2
        ///ability	2
        ///aboard	1
        ///absentee	-1
        ///absentees	-1
        ///absolve	2
        ///absolved	2
        ///absolves	2
        ///absolving	2
        ///absorbed	1
        ///abuse	-3
        ///abused	-3
        ///abuses	-3
        ///abusive	-3
        ///accept	1
        ///accepted	1
        ///accepting	1
        ///accepts	1
        ///accident	-2
        ///accidental	-2
        ///accidentally	-2
        ///accidents	-2
        ///accomplish	2
        ///accomplished	2
        ///accomplishes	2
        ///accusation	-2
        ///accusations	-2
        ///accuse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AFINN_111 {
            get {
                return ResourceManager.GetString("AFINN_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Valence
        ///_intercept	0
        ///abandon	-2
        ///abandons	-2
        ///abandoned	-2
        ///absentee	-1
        ///absentees	-1
        ///aboard	1
        ///abducted	-2
        ///abduction	-2
        ///abductions	-2
        ///abuse	-3
        ///abused	-3
        ///abuses	-3
        ///accept	1
        ///accepting	1
        ///accepts	1
        ///accepted	1
        ///accident	-2
        ///accidental	-2
        ///accidentally	-2
        ///accidents	-2
        ///accomplish	2
        ///accomplished	2
        ///accomplishes	2
        ///accusation	-2
        ///accusations	-2
        ///accuse	-2
        ///accused	-2
        ///ache	-2
        ///achievable	1
        ///acquitted	2
        ///admit	-1
        ///admits	-1
        ///admitted	-1
        ///adopt	1
        ///adopts	1
        ///advanced	1
        ///affected	-1
        ///afraid	-2
        ///ag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AFINN_96 {
            get {
                return ResourceManager.GetString("AFINN_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	M
        ///_intercept	0
        ///authentic	95
        ///genuine	92
        ///real	88
        ///skilled	83
        ///faithful	81
        ///legitimate	81
        ///original	80
        ///traditional	79
        ///pure	78
        ///historical	77
        ///sincere	77
        ///craftsmanship	74
        ///honest	74
        ///integrity	74
        ///quintessential	74
        ///expert	73
        ///iconic	73
        ///inspiring	73
        ///unique	72
        ///wholesome	72
        ///professional	70
        ///skillful	70
        ///truthful	68
        ///unmistakable	68
        ///artisan	67
        ///unpretentious	67
        ///heartful	66
        ///delicious	65
        ///virtuous	64
        ///normal	63
        ///creative	62
        ///interesting	62
        ///orthodox	62
        ///artful	60
        ///special	60
        ///righteous	58
        ///subst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthenticityNorms {
            get {
                return ResourceManager.GetString("AuthenticityNorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Concreteness
        ///_intercept	0
        ///a	1.46
        ///aardvark	4.68
        ///aback	1.65
        ///abacus	4.52
        ///abandon	2.54
        ///abandoned	2.52
        ///abandonee	2.92
        ///abandoner	2.5
        ///abandonment	2.54
        ///abasement	1.67
        ///abatement	1.92
        ///abbreviate	2.59
        ///abbreviated	3.1
        ///abbreviation	3.07
        ///abdicate	2.08
        ///abdomen	4.7
        ///abdominal	4.28
        ///abdominally	3.15
        ///abduct	2.88
        ///abductee	3.27
        ///abduction	3.07
        ///abductor	3.89
        ///abhor	1.81
        ///abhorrence	2.15
        ///abhorrently	2.04
        ///abhorring	1.68
        ///abide	1.68
        ///abiding	2.07
        ///abidingly	1.82
        ///ability	1.81
        ///abject	1.67
        ///ablaze	3.82        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrysbaertConcreteness {
            get {
                return ResourceManager.GetString("BrysbaertConcreteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Afraid_Freq	Amused_Freq	Angry_Freq	Annoyed_Freq	Dont_Care_Freq	Happy_Freq	Inspired_Freq	Sad_Freq	Afraid_Normfreq	Amused_Normfreq	Angry_Normfreq	Annoyed_Normfreq	Dont_Care_Normfreq	Happy_Normfreq	Inspired_Normfreq	Sad_Normfreq	Afraid_Tfidf	Amused_Tfidf	Angry_Tfidf	Annoyed_Tfidf	Dont_Care_Tfidf	Happy_Tfidf	Inspired_Tfidf	Sad_Tfidf
        ///_intercept	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///0	0.091040449	0.101889368	0.167116461	0.065455893	0.135220504	0.291063671	0.064974737	0.083238917	0.087696832	0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DepecheMood {
            get {
                return ResourceManager.GetString("DepecheMood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Valence	Arousal	Dominance	Concreteness	Imagery
        ///_intercept	0	0	0	0	0
        ///aback	5.2	4.58	4.93	4.19	4.58
        ///abacus	5.97	4.66	5.39	5.02	5.11
        ///abalone	5.39	5.21	4.88	5.76	5.43
        ///abandon	4.33	5.75	5.01	3.07	3.97
        ///abandoned	4.76	4.86	4.75	4.58	4.77
        ///abandonment	3.39	5.51	4.22	3.18	4.18
        ///abash	5.42	4.83	5.07	4.37	4.97
        ///abate	3.38	5.47	4.38	3.2	4.18
        ///abbey	6.12	5.14	5.63	5.05	4.97
        ///abbot	5.98	5.14	5.46	4.41	4.68
        ///abbreviate	5.81	4.54	5.33	4.2	4.36
        ///abbreviation	5.95	4.52	5.32	4.63	4.62
        ///abdicate	4.44	5.79	4.96	4	4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DICLSA {
            get {
                return ResourceManager.GetString("DICLSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Embodiment_M	Embodiment_SD
        ///_intercept	0	0
        ///absorb	3.23	1.73
        ///abuse	5.19	1.58
        ///accept	2.78	1.68
        ///accuse	2.97	1.49
        ///achieve	3.2	1.83
        ///acknowledge	2.86	1.82
        ///act	5.45	1.69
        ///adapt	4.14	1.73
        ///add	3.2	1.66
        ///adjust	3.55	1.61
        ///admire	3.33	1.99
        ///admonish	3.03	1.3
        ///adopt	3.49	1.93
        ///adore	3.45	1.67
        ///advise	3.31	1.97
        ///affirm	2.74	1.61
        ///afford	2.58	1.82
        ///agree	3.16	1.75
        ///aid	3.87	1.45
        ///ail	3.69	1.77
        ///align	3.14	1.56
        ///allot	2.71	1.62
        ///allow	3	1.65
        ///alter	3.39	1.63
        ///amaze	3.17	1.85
        ///amend	2.42	1.34
        ///amuse	3.39	1.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Embodiment {
            get {
                return ResourceManager.GetString("Embodiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Care_Score	Fairness_Score	Loyalty_Score	Authority_Score	Sanctity_Score	Care_Sentiment	Fairness_Sentiment	Loyalty_Sentiment	Authority_Sentiment	Sanctity_Sentiment
        ///_intercept	0	0	0	0	0	0	0	0	0	0
        ///brought	0.18	0.114285714	0.08	0.096551724	0.053333333	-0.235403704	-0.310015	-0.099783333	-0.402207143	-0.13255
        ///close	0.073359073	0.031372549	0.115384615	0.077220077	0.084821429	0.136189474	-0.0439625	-0.011386667	-0.258195	0.100926316
        ///marine	0.029850746	0.011764706	0.043859649	0.009433962	0	-0.39225	-0.025 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eMFD {
            get {
                return ResourceManager.GetString("eMFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word	Valence	Extremity	Emotionality	Valence_StdDev	Extremity_StdDev	Emotionality_StdDev
        ///_intercept	0	0	0	0	0	0
        ///awesome	8.57	4.07	6.34	0.63	0.63	2.44
        ///awesomeness	8.46	3.96	6.72	0.92	0.92	2.12
        ///best	8.45	3.95	4.07	1.09	1.09	2.95
        ///peace	8.44	3.94	3.78	1.22	1.09	2.44
        ///magnificent	8.44	3.94	5.00	0.95	0.95	3.22
        ///beautiful	8.41	3.91	5.81	0.91	0.91	2.45
        ///brilliant	8.40	3.90	3.83	0.87	0.87	2.59
        ///extraordinary	8.36	3.86	5.41	1.04	1.04	1.82
        ///miraculous	8.36	3.86	3.72	0.81	0.81	3.17
        ///adore	8.34	3.84	6.48	1.04	1.04	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluativeLexicon2 {
            get {
                return ResourceManager.GetString("EvaluativeLexicon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	mean	sd	mean_M	sd_M	mean_F	sd_F	mean_young	sd_young	mean_old	sd_old
        ///_intercept	0	0	0	0	0	0	0	0	0	0
        ///abbey	2.292682927	1.145510856	2.176470588	1.380004263	2.347826087	0.98205238	2.391304348	1.196173081	2.166666667	1.098126747
        ///abode	2.413793103	1.118584609	2.1	0.994428926	2.578947368	1.169795304	2.692307692	1.182131929	2.1875	1.046820583
        ///abscess	1.59375	1.042929342	1.625	1.187734939	1.583333333	1.017954755	1.555555556	1.041617646	1.642857143	1.081817762
        ///absence	1.64	0.952190457	1.615384615	0.960768 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Humor {
            get {
                return ResourceManager.GetString("Humor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Happiness_Rank	Happiness_M	Happiness_SD	Twitter_Rank	Google_Rank	NYT_Rank	Lyrics_Rank
        ///_intercept	0	0	0	0	0	0	0
        ///laughter	1	8.50	0.9313	3600			1728
        ///happiness	2	8.44	0.9723	1853	2458		1230
        ///love	3	8.42	1.1082	25	317	328	23
        ///happy	4	8.30	0.9949	65	1372	1313	375
        ///laughed	5	8.26	1.1572	3334	3542		2332
        ///laugh	6	8.22	1.3746	1002	3998	4488	647
        ///laughing	7	8.20	1.1066	1579			1122
        ///excellent	8	8.18	1.1008	1496	1756	3155	
        ///laughs	9	8.18	1.1551	3554			2856
        ///joy	10	8.16	1.0568	988	2336	2723	809
        ///successful	11	8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabMT_Norms {
            get {
                return ResourceManager.GetString("LabMT_Norms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Auditory_M	Gustatory_M	Haptic_M	Interoceptive_M	Olfactory_M	Visual_M	Foot_leg_M	Hand_arm_M	Head_M	Mouth_M	Torso_M	Auditory_MSD	Gustatory_MSD	Haptic_MSD	Interoceptive_MSD	Olfactory_MSD	Visual_MSD	Foot_leg_MSD	Hand_arm_MSD	Head_MSD	Mouth_MSD	Torso_MSD	MaxStrength_Perceptual	Minkowski3_Perceptual	Exclusivity_Perceptual	MaxStrength_Action	Minkowski3_Action	Exclusivity_Action	MaxStrength_Sensorimotor	Minkowski3_Sensorimotor	Exclusivity_Sensorimotor	N_Known_Perceptual	List_N_Perceptual	Pct_Known_Perceptual [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LancasterSensorimotorNorms {
            get {
                return ResourceManager.GetString("LancasterSensorimotorNorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to term	AuditoryStrengthMean	GustatoryStrengthMean	HapticStrengthMean	OlfactoryStrengthMean	VisualStrengthMean	ModalityExclusivity
        ///_intercept	0	0	0	0	0	0
        ///abrasive	1.684210526	0.578947368	3.684210526	0.578947368	2.894736842	0.329608939
        ///absorbent	0.714285714	0.476190476	3.142857143	0.476190476	4.142857143	0.409574468
        ///academy	1.411764706	0.058823529	0.470588235	0.117647059	2.705882353	0.555555556
        ///account	1.705882353	0.117647059	0.352941176	0.235294118	1.411764706	0.415384615
        ///aching	0.666666667	0.047619048	3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModalityNorms {
            get {
                return ResourceManager.GetString("ModalityNorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	gender	log_tasa_freq	log_subt_freq	log_kidbook_freq	valence	arousal	concreteness	adult_aoa
        ///_intercept	0	0	0	0	0	0	0	0
        ///able	2.6	8.2204031	3.9115	3.091042453	6.64	3.38	2.38	7.79
        ///aboard	2.714285714	5.327876169	3.1332	1.945910149			3.97	8.66
        ///above	3.1	8.07121854	3.3969	3.496507561			3.33	4.55
        ///absolutely	2.857142857	5.38907173	3.7612	3.761200116			1.97	7.08
        ///accident	3	6.00635316	3.6177	2.564949357	2.55	4.93	3.26	5.3
        ///across	2.928571429	8.492285556	3.6814	4.430816799			3.07	6.64
        ///act	2.884615385	7.33 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Molly_Lewis_Gender_Norms__2020_03_19_ {
            get {
                return ResourceManager.GetString("Molly_Lewis_Gender_Norms__2020_03_19_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemma	Authority	Care	Fairness	Loyalty	Purity
        ///_intercept	0	0	0	0	0
        ///abandon		1.6		1.428571429	
        ///abide	4.166666667				
        ///abstinence					7.714285714
        ///abstinence					4.5
        ///abuse		2.5			
        ///abuse		1.714285714			
        ///accepting			7.833333333		
        ///adulterated					2.833333333
        ///adulterine					4.111111111
        ///adultery					1.5
        ///agitation	2.8				
        ///alienate	4.285714286				
        ///allegiance				8.9	
        ///ally				8.714285714	
        ///amity		5.428571429		7.857142857	
        ///amplitude			5.166666667		
        ///annihilation		1.333333333			
        ///annihilation		1.166666667		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoralStrength {
            get {
                return ResourceManager.GetString("MoralStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Familiarity	AoA	Concreteness	Imagery
        ///_intercept	0	0	0	0
        ///biennials	340.4342822	442.0392483	392.7401914	389.3510129
        ///fawn	453.3989878	395.7684773	558.592607	602.0666396
        ///mid-week	311.6756356	658.8643591	281.2684203	246.673886
        ///nunnery	308.4862042	535.2358639	508.7936109	459.4061059
        ///localizes	286.0142728	483.7820075	302.4876695	284.266893
        ///fawe	234.9574773	495.430416	255.9148232	248.9816846
        ///poplar	405.1250501	484.5496625	582.3990538	506.6504326
        ///fleeces	317.7873517	512.7832974	490.2685345	448.633826 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PsychoLingFeat {
            get {
                return ResourceManager.GetString("PsychoLingFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Valence_Pos	Valence_Neg	Valence_Neut	Sociability_Freq	Sociability_Direction	Morality_Freq	Morality_Direction	Ability_Freq	Ability_Direction	Agency_Freq	Agency_Direction	Health_Freq	Health_Direction	Status_Freq	Status_Direction	Work_Freq	Work_Direction	Politics_Freq	Politics_Direction	Religion_Freq	Religion_Direction	Beliefs_Other_Freq	Beliefs_Other_Direction	Inhabitant_Freq	Country_Freq	Feelings_Freq	Relatives_Freq	Clothing_Freq	Ordinariness_Freq	Ordinariness_Direction	Body_Part_Freq	Body_Property_Fr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StereotypeContentDictionary {
            get {
                return ResourceManager.GetString("StereotypeContentDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Subjectivity	Confidence	Reliability	Polarity	Intensity
        ///_intercept	0	0	0	0	0
        ///13th	0	0.9		0	1
        ///20th	0	0.9		0	1
        ///21st	0	0.9		0	1
        ///2nd	0	0.9		0	1
        ///3rd	0	0.9		0	1
        ///abhorrent	0.8		0.9	-0.7	1
        ///able	0.625	0.9		0.5	1
        ///above	0.1	0.8		0	1
        ///abridged	0.5	0.8		0.1	1
        ///abrupt	1	0.9		-0.125	1
        ///absence	0		0.9	-0.0125	1
        ///absolute	0.9	0.9		0.2	1
        ///absorbed	0.9	0.8		0.3	1
        ///absorbing	0.95	0.8		0.2	1
        ///absurd	1	0.9		-0.5	1
        ///abundant	0.95	0.8		0.6	1
        ///academic	0	0.8		0	1
        ///accessible	0.375	0.9		0.375	1
        ///accomplished	0.5	0.8		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subjectivity_Lexicon_Averaged {
            get {
                return ResourceManager.GetString("Subjectivity_Lexicon_Averaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Personal_Use_M_All	Personal_Use_MSD_All	Familiarity_M_All	Familiarity_MSD_All	Offensiveness_M_All	Offensiveness_MSD_All	Tabooness_M_All	Tabooness_MSD_All	Valence_M_All	Valence_MSD_All	Arousal_M_All	Arousal_MSD_All	Imageability_M_All	Imageability_MSD_All	Personal_Use_M_Male	Personal_Use_MSD_Male	Familiarity_M_Male	Familiarity_MSD_Male	Offensiveness_M_Male	Offensiveness_MSD_Male	Tabooness_M_Male	Tabooness_MSD_Male	Valence_M_Male	Valence_MSD_Male	Arousal_M_Male	Arousal_MSD_Male	Imageability_M_Male	Image [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tabooness {
            get {
                return ResourceManager.GetString("Tabooness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Valence	Arousal	Dominance
        ///_intercept	0	0	0
        ///aardvark	6.26	2.41	4.27
        ///abalone	5.3	2.65	4.95
        ///abandon	2.84	3.73	3.32
        ///abandonment	2.63	4.95	2.64
        ///abbey	5.85	2.2	5
        ///abdomen	5.43	3.68	5.15
        ///abdominal	4.48	3.5	5.32
        ///abduct	2.42	5.9	2.75
        ///abduction	2.05	5.33	3.02
        ///abide	5.52	3.26	5.33
        ///abiding	5.57	3.59	6.6
        ///ability	7	4.85	6.55
        ///abject	4	3.94	4.35
        ///ablaze	5.15	6.75	4.58
        ///able	6.64	3.38	6.17
        ///abnormal	3.53	4.48	4.7
        ///abnormality	3.05	5	3.96
        ///abode	5.28	2.9	5.05
        ///abolish	3.84	4.18	4.65
        ///abominable	4.05	5.45	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WarrinerNorms {
            get {
                return ResourceManager.GetString("WarrinerNorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term	Weight
        ///_intercept	0
        ///86	-0.36762453
        ///187	0.71754986
        ///419	0.35754864
        ///1984	-0.92403619
        ///mar	-0.860149045
        ///abandon	-1.2974445
        ///abandoned	-0.73056376
        ///abandonment	-1.4973582
        ///abase	-0.26232919
        ///abased	0.12957497
        ///abasement	-0.43956094
        ///abash	-0.42695165
        ///abashed	-0.37630988
        ///abate	-2.4967846
        ///abatis	-0.035499173
        ///abdicate	-1.5551716
        ///abdication	-1.4990237
        ///abduct	-1.2778002
        ///aberrant	-0.95093594
        ///aberration	-1.2429533
        ///aberrometry	0.28022696
        ///abet	-1.9204496
        ///abhor	0.21297482
        ///abhorrence	-0.91331732
        ///abh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Weigand_et_al___2018____Abuse_Lexicon {
            get {
                return ResourceManager.GetString("Weigand_et_al___2018____Abuse_Lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	ReferentialActivity
        ///_intercept	0
        ///1	1
        ///2	1
        ///3	1
        ///4	1
        ///5	1
        ///6	1
        ///7	1
        ///8	1
        ///9	1
        ///10	1
        ///a	0.625
        ///able	-0.625
        ///about	-0.75
        ///accept	-0.625
        ///across	0.625
        ///afraid	1
        ///after	1
        ///again	0.25
        ///against	1
        ///age	0.625
        ///ago	0.625
        ///ah	-0.625
        ///alive	0.625
        ///all	1
        ///almost	0.25
        ///alone	-0.25
        ///along	0.625
        ///already	-1
        ///also	-1
        ///although	0.25
        ///always	-0.25
        ///am	-1
        ///an	0.625
        ///and	1
        ///angry	0.625
        ///another	1
        ///any	-0.625
        ///anybody	0.25
        ///anymore	1
        ///anyone	-0.625
        ///anything	-0.625
        ///anyway	0.25
        ///apartment	0.625
        ///appears	-1
        ///are	-1
        ///arm	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WRAD {
            get {
                return ResourceManager.GetString("WRAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	ReflReorg
        ///_intercept	0
        ///a	0.06913410200000003
        ///able	0.40354767199999997
        ///about	0.1496726260000001
        ///accept	0.2752613239999999
        ///actually	-0.10801393800000003
        ///afraid	0.0034843200000000962
        ///after	0.1789301080000001
        ///again	0.24477352000000008
        ///against	0.3855981420000001
        ///ago	-0.034456057999999956
        ///all	-0.013020355999999955
        ///almost	0.43786295
        ///alone	0.37591947400000003
        ///along	-0.39256678199999995
        ///also	0.3755675220000001
        ///although	-0.06620208999999999
        ///always	0.17976513000000005
        ///am	0.23559367399999998
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WRRL {
            get {
                return ResourceManager.GetString("WRRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	M
        ///_intercept	23.21886047
        ///raining	235.750747
        ///yellow	-71.07390168
        ///four	-27.87867583
        ///gag	-79.90197631
        ///woods	35.36102494
        ///spiders	-20.38256328
        ///friend&apos;s	47.16841195
        ///hanging	111.6901592
        ///woody	88.24605684
        ///marching	-112.7735046
        ///increase	79.40468212
        ///electricity	12.29418127
        ///funk	38.24897284
        ///lord	-128.7806988
        ///immature	-143.5951435
        ///shaving	59.37595311
        ///sinking	-63.07235007
        ///callin	37.7236519
        ///kent	125.7449987
        ///retail	74.92283531
        ///oceans	-53.64621188
        ///dell	-87.78209453
        ///crackin	-55.80408692
        ///foul	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WWBP_Age {
            get {
                return ResourceManager.GetString("WWBP_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	darktriad	machiavellianism	narcissism	psychopathy
        ///_intercept	0	0	0	0
        ///333	-0.00865131	-0.007286122	-0.026419655	-0.01247191
        ///430	0.004887096		0.015116259	
        ///530	0.004887096		0.015116259	
        ///630	0.004887096		0.015116259	
        ///730	0.004887096		0.015116259	
        ///745	0.004887096		0.015116259	
        ///830	0.004887096		0.015116259	
        ///930	0.004887096		0.015116259	
        ///1030	0.004887096		0.015116259	
        ///1130	0.004887096		0.015116259	
        ///1901	0.004037485		0.026995231	0.008422291
        ///3333	-0.00865131	-0.007286122	-0.026419655	-0.01247191        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WWBP_D3 {
            get {
                return ResourceManager.GetString("WWBP_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Distress
        ///_intercept	0
        ///helps	2.409573403
        ///uncommon	1.303017428
        ///blank	3.729931006
        ///iraqis	5.585402116
        ///explored	3.672773441
        ///concentrate	2.681559256
        ///fabrication	3.733275668
        ///vividly	3.965550217
        ///continuous	4.626951272
        ///combined	4.080281383
        ///platform	3.291627542
        ///reviews	2.828351977
        ///town	2.538721674
        ///arounf	2.321171042
        ///questioned	4.538984227
        ///per	3.479740766
        ///versus	2.169865025
        ///heavier	3.363795678
        ///weekends	1.552750803
        ///degrees	2.948586807
        ///tales	2.33988384
        ///grateful	4.591672422
        ///ambulances	5.518 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WWBP_distress_lexicon {
            get {
                return ResourceManager.GetString("WWBP_distress_lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Empathy
        ///_intercept	0
        ///helps	4.315953592
        ///uncommon	2.534964378
        ///blank	3.559862545
        ///iraqis	5.446980531
        ///explored	4.401997645
        ///concentrate	3.637599382
        ///fabrication	2.296992122
        ///vividly	4.495400781
        ///continuous	4.479186514
        ///combined	3.009020706
        ///platform	3.862354777
        ///reviews	3.279471622
        ///town	3.506233078
        ///arounf	3.580367617
        ///questioned	3.255641248
        ///per	3.939551925
        ///versus	4.295500728
        ///heavier	3.981050565
        ///weekends	2.487191302
        ///degrees	3.860214252
        ///tales	3.149696727
        ///grateful	4.956235755
        ///ambulances	5.182 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WWBP_empathy_lexicon {
            get {
                return ResourceManager.GetString("WWBP_empathy_lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	M
        ///_intercept	-0.06724152
        ///raining	-29.5501116
        ///yellow	-14.39968028
        ///four	9.067149063
        ///gag	18.82337644
        ///woods	-37.25215758
        ///hanging	61.22689817
        ///increase	-26.95924491
        ///electricity	158.2796822
        ///funk	-67.90618848
        ///lord	16.96564453
        ///shaving	-240.5289156
        ///callin	55.7136385
        ///kent	-0.774773832
        ///retail	47.59007624
        ///oceans	-17.70802544
        ///dell	-71.39680723
        ///crackin	28.68006897
        ///stabbed	17.9320548
        ///screaming	49.89193483
        ///basics	-182.3027455
        ///wednesday	12.12888733
        ///crotch	-39.9419943
        ///zzzzzz	-98.87526761
        ///commen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WWBP_Gender {
            get {
                return ResourceManager.GetString("WWBP_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word	NEG_A	NEG_E	NEG_M	NEG_P	NEG_R	POS_A	POS_E	POS_M	POS_P	POS_R
        ///_intercept	0	0	0	0	0	0	0	0	0	0
        ///january	0.03538934									
        ///sunday						0.021109368	0.098777658	0.056717648	0.134245854	0.021240506
        ///friday	0.123335733						0.032623558		0.010117429	
        ///may						0.045987017	0.036419696	0.033244923	0.063965128	0.064086652
        ///sun							0.018071812		0.102510327	
        ///wednesday									0.038398503	
        ///thursday						0.033221997		0.080644629	0.037847194	
        ///saturday							0.036685446			
        ///june						0.037892944				
        ///-	-0.046922 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WWBP_PERMA {
            get {
                return ResourceManager.GetString("WWBP_PERMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word	FUTURE_OR_NOT	PAST_OR_NOT	PRESENT_OR_NOT
        ///_intercept	-0.570547567	-0.649406376	0.236749577
        ///1	0.026305195		-0.104374144
        ///2	0.056213642		-0.205433794
        ///3		0.200019889	-0.275467506
        ///4	0.099264162		-0.395156347
        ///5		0.085203219	
        ///10			-0.053880237
        ///13		0.307564675	-0.116703527
        ///30		0.113684893	-0.095345247
        ///sunday	0.526230332		-0.439177605
        ///monday	0.390119763	-0.055367474	
        ///tuesday	0.558324626		
        ///friday	0.110221559		-0.0912179
        ///saturday	0.351791496		-0.099723911
        ///&apos;	0.003424571		-0.007303509
        ///-	-0.077647551	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WWBP_Prospection {
            get {
                return ResourceManager.GetString("WWBP_Prospection", resourceCulture);
            }
        }
    }
}
